artifacts_root: artifacts #all generation is saved in artifacts

data_ingestion: #allows changes here which reflect everywhere
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/CatterPingu/Programs/raw/main/samsumdata.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train","test","validation"]



data_transformation:
  root_dir: artifacts/data_tansformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail
